# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.6-cli-stretch
        name: app
      - image: circleci/mysql:8.0.4
        name: db
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_DATABASE: test_database
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
      - image: elasticsearch:6.8.0
        name: elasticsearch
    steps:

      # checkout source code
      - checkout

      - run: sudo apt-get install -y libpng-dev zziplib-bin zlib1g-dev
      - run: sudo docker-php-ext-install gd pdo pdo_mysql mysqli
      - run: sudo composer self-update

      # pack es module files into subfolder
      - run: sudo mkdir ../ElasticsearchFeeder && sudo mv * ../ElasticsearchFeeder

      # Install wireshell
      - run: sudo composer global require wireshell/wireshell

      # Install ProcessWire
      - run: sudo /root/.composer/vendor/bin/wireshell new processwire --profile=default --dbEngine=InnoDB --dbHost=db --dbUser=test_user --dbPass=test_password --dbName=test_database --timezone=Europe/Berlin --httpHosts=localhost --username=admin --userpass=Test123 --useremail=john.doe@acme.com

      # Move ES module into pw module folder
      - run: sudo mv ../ElasticsearchFeeder processwire/site/modules/

      # enable module
      - run: sudo /root/.composer/vendor/bin/wireshell module:enable ElasticsearchFeeder
