# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.6-cli-stretch
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_DATABASE: test_database
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_HOST: 127.0.0.1
      - image: elasticsearch:6.8.0
    steps:

      # checkout source code
      - checkout

      - run: sudo apt-get install -y libpng-dev zziplib-bin zlib1g-dev mysql-shell
      - run: sudo docker-php-ext-install gd pdo pdo_mysql mysqli
      - run: sudo composer self-update

      # Install wireshell
      - run: sudo composer global require wireshell/wireshell

      # Install ProcessWire
      - run: sudo /root/.composer/vendor/bin/wireshell new processwire --profile=default --dbUser=test_user --dbPass=test_password --dbName=test_database --timezone=Europe/Berlin --httpHosts=127.0.0.1 --username=admin --userpass=Test123 --useremail=john.doe@acme.com
